# =============================================
# Prometheus Configuration for CloudPulse
# =============================================

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cloudpulse-app'
    metrics_path: '/actuator/prometheus'
    honor_labels: true
    static_configs:
      - targets: ['app:8080']
